name: todays-recipe

options:
  bundleIdPrefix: com.kagehito
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: ja
  xcodeVersion: "13.4.1"

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: 0.47.0

targets:
  todays-recipe:
    type: application
    platform: iOS
    sources:
      - todays-recipe
    settings:
      base:
        INFOPLIST_FILE: todays-recipe/Info.plist
        DEVELOPMENT_LANGUAGE: jp
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        debug:
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=50
    dependencies:
      - package: ComposableArchitecture

  todays-recipeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - todays-recipeTests
    dependencies:
      - target: todays-recipe

  todays-recipeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - todays-recipeUITests
    dependencies:
      - target: todays-recipe

schemes:
  todays-recipe:
    build:
      targets:
        todays-recipe: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - todays-recipe
      targets:
        - name: todays-recipeTests
          parallelizable: true
          randomExecutionOrder: true
        - name: todays-recipeUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
